# pyproject.toml for modern Python tooling (linting, formatting, etc.)
# setup.py handles package building and installation

[tool.black]
line-length = 88
target-version = ['py36']

[tool.isort]
profile = "black"
line_length = 88

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]

# Note: Package metadata and build configuration are in setup.py